name: CI # Nome do fluxo
on: push # Evento que dispara o fluxo
jobs:
  rspec: # Identificador do job
    ... # Opçòes de configuração do job
    name: RSpec
    needs:
    runs-on: ubuntu-20.04
  env:
  RAILS_ENV: test
  DATABASE_URL: postgres://postgres:example@localhost:5432/db_test
  services:
    postgres:
      image: postgres:latest
      ports: ['5432:5432']
      env:
        POSTGRES_DB: db_test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: example
      options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install postgres client dependencies
        run: sudo apt-get install libpq-dev

      - name: Create database
      run: |
        bundle exec rails db:create
        # Se o projeto usar `schema.rb`
        bundle exec rails db:schema:load
        # Se o projeto usar `structure.sql`
        bundle exec rails db:structure:load
        # Se o projeto não usar nenhum dos dois
        bundle exec rails db:migrate

      - name: Run tests
        run: bundle exec rspec spec
